name: Update ZZZ Widget

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Run ZZZ Widget Updater
        run: node zzzUser.js
        env:
          APP_ID: ${{ secrets.APP_ID }}
          DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}
          TOKEN: ${{ secrets.TOKEN }}
          HOYO_LTOKEN_V2: ${{ secrets.HOYO_LTOKEN_V2 }}
          HOYO_LTUID_V2: ${{ secrets.HOYO_LTUID_V2 }}
          ZZZ_ID: ${{ secrets.ZZZ_ID }}
          HOYOLAB_ID: ${{ secrets.HOYOLAB_ID }}
